---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-cron-tabs-admin-edit 
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
rules:
- apiGroups: ["openshift.cloudfirst.dev"] 
  resources: ["migrations"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"] 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-cron-tabs-view 
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
rules:
- apiGroups: ["openshift.cloudfirst.dev"] 
  resources: ["migrations"] 
  verbs: ["get", "list", "watch"]